name: Deploy CI/CD

on:
  push: # tells github to run this on any push to the repository
    branches:
      - staging

jobs:
    docker_demo:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:latest
        steps:
            -   uses: actions/checkout@v3
            -   run: ls #apt update && apt install -y openssh-client git
            -   name: Setup key
                uses: ./
                with:
                    ssh-private-key: |
                        ${{ secrets.STAGING_KEY }}
            -   run: |
                    cd /home/frappe/frappe-bench/ # we move into our app's folder
                    git pull upstream staging # we pull any changes from git
                    bench setup requirements
                    sudo supervisorctl restart all # we remove any unused dependencies
                    bench migrate # sync database
                    bench doctor
                    
