name: Deploy CI/CD

on:
  push: # tells github to run this on any push to the repository
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: CICD-STAGING # this job depends on "test" having finished
    #if: github.event.push == true # we tell Github to only execute this step if we're on our master branch (so we don't put unfinished branches in production)
    steps:
      - name: Deploying to My Droplet
        uses: webfactory/ssh-agent@v0.7.0 # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          ssh-private-key: ${{ secrets.STAGING_KEY }}
          script: |
            cd /home/frappe/frappe-bench/ # we move into our app's folder
            git pull upstream staging # we pull any changes from git
            bench setup requirements
            sudo supervisorctl restart all # we remove any unused dependencies
            bench migrate # sync database
            bench doctor
